version: '3.12'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: movie_app
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ${PWD}:/usr/src/app
    ports:
      - "8000:8000"
    env_file:
      .env

  database:
    image: postgres:15
    restart: always
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5000:5432"
    env_file:
      .env

volumes:
  pg_data:
