# Generated by Django 5.0.6 on 2024-07-09 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apidemo', '0002_product_owner_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='owner',
        ),
    ]
